[package]
name = "ryde"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "crates/css",
  "crates/css_macros",
  "crates/db",
  "crates/db_macros",
  "crates/html",
  "crates/router",
  "crates/router_macros",
  "crates/static_files",
  "crates/static_files_macros",
]

[workspace.dependencies]
css = { path = "crates/css", version = "0.1.0" }
db = { path = "crates/db", version = "0.1.0" }
html = { path = "crates/html", version = "0.2.0" }
router = { path = "crates/router", version = "0.1.0" }
static_files = { path = "crates/static_files", version = "0.2.0" }

[dependencies]
axum = { version = "0.7.4", features = ["macros"] }
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }
axum-extra = { version = "0.9.2", features = ["cookie", "typed-header"] }
css = { workspace = true }
db = { workspace = true }
html = { workspace = true }
router = { workspace = true }
static_files = { workspace = true }


[[example]]
name = "simple"

[[example]]
name = "html"

[[example]]
name = "router"

[[example]]
name = "static_files"

[[example]]
name = "db"
