[package]
name = "ryze"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.4", features = ["macros"] }
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }
hyped = { version = "0.1.1" }
enum_router = { path = "enum_router" }

[[example]]
name = "simple"

[[example]]
name = "html"

[[example]]
name = "router"
